base_model: ./curr-model
base_model_config: ./curr-model
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
# tokenizer_padding_side: left
is_mistral_derived_model: true

load_in_8bit: true
load_in_4bit: false
strict: false
device_map: auto

datasets:
  - path: prepared-dataset.jsonl
    ds_type: json
    type: completion
    overlap_len: 6000
    # min_sample_len: 1000
  - path: prepared-instr-dataset.jsonl
    ds_type: json
    type:
      system_prompt: ""
      field_system: system
      format: "### Instruction: {instruction}\n\n### Input: {input}\n\n### Response: "
      no_input_format: "### Instruction: {instruction}\n\n### Response: "
dataset_prepared_path: last_run_prepared
val_set_size: 0.01
output_dir: ./mistral-out

adapter: lora
lora_model_dir:

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

lora_r: 128
lora_alpha: 64
lora_dropout: 0.0
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:
# noisy_embedding_alpha: 5 # TEMP removed as axolotl is broken

wandb_project:
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 2
num_epochs: 2
optimizer: adamw_bnb_8bit
lr_scheduler: constant_with_warmup
learning_rate: 0.000055

train_on_inputs: true
group_by_length: false
bf16: true
fp16: false
tf32: true

gradient_checkpointing: true
early_stopping_patience:
# resume_from_checkpoint:
# auto_resume_from_checkpoints: true
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
safe_serialization: true

warmup_steps: 20
eval_steps: 128
eval_table_size:
save_steps: 128
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
